#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load nvm and use correct Node version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm use 20 >/dev/null

yarn test
yarn lint
yarn format
